---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r setup}
pacman::p_load(dplyr, magrittr, ggplot2)

data <- openxlsx::read.xlsx("Survey71_Creative_09-05-24.xlsx",sheet = "reshape",colNames = TRUE,check.names = TRUE)

data <- data %>%
  janitor::clean_names()

```


```{r transform_long}

# transform the format
data_long <- data %>%
  select(c(x1:strongly_agree)) %>%
  tidyr::gather(data, group, strongly_disagree:strongly_agree) %>%
  arrange(factor(x1, levels = c("strongly_disagree", "disagree", "neither_agree_nor_disagree", "agree", "strongly_agree"))) %>% 
  mutate(x1=factor(x1, levels=unique(x1)))

```

```{r plot}

pacman::p_load(HH)


data_sum <- data %>%
  dplyr::rename(Item = x1) %>%
    dplyr::select(Item:strongly_agree) %>%
    mutate(across(c(-Item), ~.x*100)) %>%
  dplyr::rename("Strongly Disagree" = strongly_disagree,
                "Disagree" = disagree,
                "Neither agree nor disagree" = neither_agree_nor_disagree, 
                "Agree" = agree,
                "Strongly Agree" = strongly_agree)



#rownames(data_sum) <- data_sum$Item

data_sum <- data_sum %>%
  rowwise() %>%
  mutate(Item_orig = Item,
         Item = stringr::str_wrap(Item_orig, width = 60))


data_sum <- data_sum %>%
  mutate(Item = factor(Item, levels = c(Item)))

x <- HH::likertplot(data_sum[2:6], 
               horizontal=TRUE,
               main="NTEU member feedback",
               sub= list("n=63 responses q.3-8, and n=62 q.9-12",
                         cex = .4,
                         col = "blue"),
               xlab = list("%",
                           cex = .4),
               #ylab = "Q",
               
               par.strip.text=list(cex=.4, lines=5, rotate=30),
               auto.key=list(space="right", 
                             columns=1,
                             cex = .5), 
               #padding.text=2),
               strip = FALSE,
               add.text = T,
               xlim = c(-100,100),
               scales = list(x = list(rot = 45,
                                      cex = .6,
                                      at=seq(-90,90,10)),
                             y = list(cex = .6,
                                      labels = rev(c(data_sum$Item))))
)





```




```{r junk}


# Stacked + percent
data_long %>%
  dplyr::rename(Item = x1) %>%
  dplyr::mutate(group = group*100) %>%
  ggplot(., aes(fill=data, y=group, x=Item)) + 
    geom_bar(position="stack", stat="identity") +
    coord_flip() +  # (1) Flipping the axis
  theme_minimal() +  # (3) Changing the theme to a modern accessible alternative standard
  scale_fill_viridis_d() +
    scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 10))

plot(likert(summary=data_sum))

%>%
  HH::likert(Item~.,
             data[1:6],
             ReferenceZero = 3,
          horizontal=TRUE,
           aspect=1.5,
           main="Here the plot",
           auto.key=list(space="right", 
                         columns=1,
                         reverse=TRUE, 
                         padding.text=2
                         ),
           sub="Here some words"
           )

HH::likert(data_long, 
           horizontal=TRUE,
           aspect=1.5,
           main="Here the plot",
           auto.key=list(space="right", 
                         columns=1,
                         reverse=TRUE, 
                         padding.text=2
                         ),
           sub="Here some words"
           )


```

